export const config = {
  port: Number(process.env.PORT || 3000),
  jwtSecret: process.env.JWT_SECRET || "dev-jwt-secret",
  baseChainId: Number(process.env.BASE_CHAIN_ID || 84532),
  storageBackend: (process.env.STORAGE_BACKEND || "memory").toLowerCase(),
  databaseUrl: process.env.DATABASE_URL || "",
  siweMode: (process.env.SIWE_MODE || "mock").toLowerCase(),
  siweDomain: process.env.SIWE_DOMAIN || "localhost",
  siweUri: process.env.SIWE_URI || "http://localhost",
  siweStatement: process.env.SIWE_STATEMENT || "Sign in to Agent Mail Cloud",
  siweChallengeTtlMs: Number(process.env.SIWE_CHALLENGE_TTL_MS || 5 * 60 * 1000),
  paymentMode: (process.env.PAYMENT_MODE || "mock").toLowerCase(),
  paymentHmacSecret: process.env.X402_HMAC_SECRET || "",
  paymentHmacSkewSec: Number(process.env.X402_HMAC_SKEW_SEC || 300),
};
